import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = { x = 10, y = 10 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Regular" }
italic = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Beam", blinking = "On"}

[mouse]
hide_when_typing = true
